#!/bin/sh

start() {
  dropbear -B
}

stop() {
  killall dropbear
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?